name: Deploy Azure Function

on:
  push:
    branches:
      - main  # Certifique-se de que sua branch principal se chama 'main'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Setup DotNet 8.0'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: 'Restore Dependencies'
        run: dotnet restore PipelineDocAuditor.csproj

      - name: 'Build Project'
        run: dotnet build PipelineDocAuditor.csproj --configuration Release

      - name: 'Publish Project'
        run: dotnet publish PipelineDocAuditor.csproj --configuration Release --output ./publish

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        with:
          app-name: 'Function-Leandro' # <--- Troque pelo nome da sua Function na Azure
          package: ./publish
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}